# Generated by Django 2.0 on 2018-09-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPRetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('exception_info', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('app_id', models.IntegerField()),
            ],
            options={'ordering': ('-created_timestamp',), 'verbose_name_plural': 'HttpRetry'},
        ),
        migrations.AlterUniqueTogether(
            name='httpretry',
            unique_together={('content_type', 'object_id', 'app_id')},
        ),
    ]
